name: "CI"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Format code with Spotless & suggested WPI formatting
  # https://docs.wpilib.org/en/stable/docs/software/advanced-gradlerio/code-formatting.html
  format:
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 17
      - run: ./gradlew spotlessApply
      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "Automated code formatting"
          file_pattern: "*.java"
  # Lint code with Spotless as suggested by WPI
  # See above
  lint:
    runs-on: ubuntu-22.04
    needs: format
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 17
      - run: ./gradlew spotlessCheck
  # Build with WPI Cross-compile for CI
  # https://docs.wpilib.org/en/stable/docs/software/advanced-gradlerio/robot-code-ci.html
  build:
    runs-on: ubuntu-22.04
    container: wpilib/roborio-cross-ubuntu:2025-22.04
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Add repository to git safe directories
        run: git config --global --add safe.directory $GITHUB_WORKSPACE
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Compile and run tests on robot code
        run: ./gradlew build jar
      - name: Archive final artifacts
        uses: actions/upload-artifact@v4
        with:
          name: java-swerve-template
          path: |
            build/libs/java-swerve-template.jar
